name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests: 
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.1-alpine
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a health check
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Run Regular Test Suite
      run: MIN_WIDTH=100 bin/specs -t -c
    - uses: ./
      id: cpu-count
    - name: Run Tests in Parallel 
      run: |
        export CPU_COUNT="$(cat /proc/cpuinfo | grep processor | wc -l)"
        echo "running with CPU_COUNT of ${CPU_COUNT}"
        MIN_WIDTH=100 .bats-prefix/bin/bats --pretty -T -j "${CPU_COUNT:-8}" $(find test -name '*_test.bats' -type f)

  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install ShellCheck
      run: |
        scversion="stable" # or "v0.4.7", or "latest"
        wget -qO- "https://github.com/koalaman/shellcheck/releases/download/${scversion?}/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv
        mkdir -p ${HOME}/bin
        cp -v "shellcheck-${scversion}/shellcheck"  ${HOME}/bin
        ${HOME}/bin/shellcheck --version
    - name: Run ShellCheck
      run: |
        ${HOME}/bin/shellcheck -a $(find {bin,lib} -type f) || true
        echo; echo; echo
        ${HOME}/bin/shellcheck -a $(find {bin,lib} -type f) |  egrep -c '^In ' || true

